# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='given_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_given_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
