# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comodo', '0002_auto_20160322_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_reserved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
